import { User, UserStatus } from "@/@types/users";

export const userData: User[] = [
  {
    id: 1,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.ACTIVE,
  },
  {
    id: 2,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.BANNED,
  },
  {
    id: 3,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.ACTIVE,
  },
  {
    id: 4,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.BANNED,
  },
  {
    id: 5,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.ACTIVE,
  },
  {
    id: 6,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.ACTIVE,
  },
  {
    id: 7,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.BANNED,
  },
  {
    id: 8,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.ACTIVE,
  },
  {
    id: 9,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.ACTIVE,
  },
  {
    id: 10,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.EMAIL_UNVERIFIED,
  },
  {
    id: 11,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.ACTIVE,
  },
  {
    id: 12,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.ACTIVE,
  },
  {
    id: 13,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.BANNED,
  },
  {
    id: 14,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.ACTIVE,
  },
  {
    id: 15,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.ACTIVE,
  },
  {
    id: 16,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.BANNED,
  },
  {
    id: 17,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.ACTIVE,
  },
  {
    id: 18,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.EMAIL_UNVERIFIED,
  },
];

export const activeUserData: User[] = [
  {
    id: 1,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.ACTIVE,
  },
  {
    id: 2,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.ACTIVE,
  },
  {
    id: 3,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.ACTIVE,
  },
  {
    id: 4,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.ACTIVE,
  },
  {
    id: 5,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.ACTIVE,
  },
  {
    id: 6,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.ACTIVE,
  },
  {
    id: 7,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.ACTIVE,
  },
  {
    id: 8,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.ACTIVE,
  },
  {
    id: 9,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.ACTIVE,
  },
  {
    id: 10,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.ACTIVE,
  },
  {
    id: 11,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.ACTIVE,
  },
  {
    id: 12,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.ACTIVE,
  },
  {
    id: 13,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.ACTIVE,
  },
  {
    id: 14,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.ACTIVE,
  },
  {
    id: 15,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.ACTIVE,
  },
  {
    id: 16,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.ACTIVE,
  },
  {
    id: 17,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.ACTIVE,
  },
  {
    id: 18,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.ACTIVE,
  },
];
export const unverifiedUserData: User[] = [
  {
    id: 1,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.EMAIL_UNVERIFIED,
  },
  {
    id: 2,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.EMAIL_UNVERIFIED,
  },
  {
    id: 3,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.EMAIL_UNVERIFIED,
  },
  {
    id: 4,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.EMAIL_UNVERIFIED,
  },
  {
    id: 5,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.EMAIL_UNVERIFIED,
  },
  {
    id: 6,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.EMAIL_UNVERIFIED,
  },
  {
    id: 7,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.EMAIL_UNVERIFIED,
  },
  {
    id: 8,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.EMAIL_UNVERIFIED,
  },
  {
    id: 9,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.EMAIL_UNVERIFIED,
  },
  {
    id: 10,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.EMAIL_UNVERIFIED,
  },
  {
    id: 11,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.EMAIL_UNVERIFIED,
  },
  {
    id: 12,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.EMAIL_UNVERIFIED,
  },
  {
    id: 13,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.EMAIL_UNVERIFIED,
  },
  {
    id: 14,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.EMAIL_UNVERIFIED,
  },
  {
    id: 15,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.EMAIL_UNVERIFIED,
  },
  {
    id: 16,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.EMAIL_UNVERIFIED,
  },
  {
    id: 17,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.EMAIL_UNVERIFIED,
  },
  {
    id: 18,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.EMAIL_UNVERIFIED,
  },
];
export const bannedUserData: User[] = [
  {
    id: 1,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.BANNED,
  },
  {
    id: 2,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.BANNED,
  },
  {
    id: 3,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.BANNED,
  },
  {
    id: 4,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.BANNED,
  },
  {
    id: 5,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.BANNED,
  },
  {
    id: 6,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.BANNED,
  },
  {
    id: 7,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.BANNED,
  },
  {
    id: 8,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.BANNED,
  },
  {
    id: 9,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.BANNED,
  },
  {
    id: 10,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.BANNED,
  },
  {
    id: 11,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.BANNED,
  },
  {
    id: 12,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.BANNED,
  },
  {
    id: 13,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.BANNED,
  },
  {
    id: 14,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.BANNED,
  },
  {
    id: 15,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.BANNED,
  },
  {
    id: 16,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.BANNED,
  },
  {
    id: 17,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.BANNED,
  },
  {
    id: 18,
    username: "Johnny Test",
    email: "johnnytest@gmail.com",
    phone: "+1 (234) 567 8910",
    status: UserStatus.BANNED,
  },
];
