export const sampleLocations = [
  {
    id: "LOC-332123",
    name: "Lumpur Airport",
    country: "Nigeria",
    service_days: "Sunday - Monday",
    service_hours: "9:00am - 5:00pm",
    address: "Block C, Gate 5, Lumpur Airport, Cassabalinca",
    status: "Inactive",
  },
  {
    id: "LOC-332123",
    name: "Lumpur Airport",
    country: "Ghana",
    service_days: "Sunday - Monday",
    service_hours: "9:00am - 5:00pm",
    address: "Block C, Gate 5, Lumpur Airport, Cassabalinca",
    status: "active",
  },
  {
    id: "LOC-332123",
    name: "Lumpur Airport",
    country: "Kenya",
    service_days: "Monday - Friday",
    service_hours: "9:00am - 5:00pm",
    address: "Block C, Gate 5, Lumpur Airport, Cassabalinca",
    status: "active",
  },
  {
    id: "LOC-332123",
    name: "Lumpur Airport",
    country: "Nigeria",
    service_days: "Sunday - Monday",
    service_hours: "9:00am - 5:00pm",
    address: "Block C, Gate 5, Lumpur Airport, Cassabalinca",
    status: "active",
  },
  {
    id: "LOC-332123",
    name: "Lumpur Airport",
    country: "Ghana",
    service_days: "Monday - Friday",
    service_hours: "9:00am - 5:00pm",
    address: "Block C, Gate 5, Lumpur Airport, Cassabalinca",
    status: "Inactive",
  },
  {
    id: "LOC-332123",
    name: "Lumpur Airport",
    country: "Kenya",
    service_days: "Sunday - Monday",
    service_hours: "9:00am - 5:00pm",
    address: "Block C, Gate 5, Lumpur Airport, Cassabalinca",
    status: "active",
  },
  {
    id: "LOC-332123",
    name: "Lumpur Airport",
    country: "Nigeria",
    service_days: "Sunday - Monday",
    service_hours: "9:00am - 5:00pm",
    address: "Block C, Gate 5, Lumpur Airport, Cassabalinca",
    status: "Inactive",
  },
  {
    id: "LOC-332123",
    name: "Lumpur Airport",
    country: "Ghana",
    service_days: "Sunday - Monday",
    service_hours: "9:00am - 5:00pm",
    address: "Block C, Gate 5, Lumpur Airport, Cassabalinca",
    status: "active",
  },
  {
    id: "LOC-332123",
    name: "Lumpur Airport",
    country: "Kenya",
    service_days: "Sunday - Monday",
    service_hours: "9:00am - 5:00pm",
    address: "Block C, Gate 5, Lumpur Airport, Cassabalinca",
    status: "active",
  },
  {
    id: "LOC-332123",
    name: "Lumpur Airport",
    country: "Nigeria",
    service_days: "Monday - Friday",
    service_hours: "9:00am - 5:00pm",
    address: "Block C, Gate 5, Lumpur Airport, Cassabalinca",
    status: "active",
  },
  {
    id: "LOC-332123",
    name: "Lumpur Airport",
    country: "Ghana",
    service_days: "Sunday - Monday",
    service_hours: "9:00am - 5:00pm",
    address: "Block C, Gate 5, Lumpur Airport, Cassabalinca",
    status: "active",
  },
  {
    id: "LOC-332123",
    name: "Lumpur Airport",
    country: "Kenya",
    service_days: "Monday - Friday",
    service_hours: "9:00am - 5:00pm",
    address: "Block C, Gate 5, Lumpur Airport, Cassabalinca",
    status: "active",
  },
  {
    id: "LOC-332123",
    name: "Lumpur Airport",
    country: "Nigeria",
    service_days: "Sunday - Monday",
    service_hours: "9:00am - 5:00pm",
    address: "Block C, Gate 5, Lumpur Airport, Cassabalinca",
    status: "active",
  },
];
